# Generated by Django 3.1.2 on 2020-11-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quizzes',
        ),
    ]
